version: "3.7"
services:
    www:
        image: nimmis/apache-php7
        ports: 
            - "8080:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db:docker_host
        restart: always 
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: mrbs
            MYSQL_USER: mrbs
            MYSQL_PASSWORD: mrbs-password
            MYSQL_ROOT_PASSWORD: root-password 
        volumes:
            - ./init_db:/docker-entrypoint-initdb.d
            - mrbs_db:/var/lib/mysql
        restart: always 
volumes:
    mrbs_db:

